### ISSUE TITLE
Would you like to share distilled datasets ?

### ISSUE THREAD

**Issue by boom-R123** [thu-coai/DA-Transformer#4]
Hi,
Thanks for your nice paper and code!
Would you like to share the distilled datasets used in this paper?

**Comment by hzhwcmhf** [comment]
Yes. You can download our distilled data from the following links. All data are distilled from Transformer-big.

_ | _ | _ | _
--- | --- | --- | ---
WMT14 | [En-De](https://cloud.tsinghua.edu.cn/f/530035ff33134f30b7c2/?dl=1) | [De-En](https://cloud.tsinghua.edu.cn/f/3276f187ac434c9f9c98/?dl=1) | [validtest](https://cloud.tsinghua.edu.cn/f/dfca2a8c53274d5eab01/?dl=1)
WMT17 | [Zh-En](https://cloud.tsinghua.edu.cn/f/33fb2d2bbc2649de84f1/?dl=1) | [En-Zh](https://cloud.tsinghua.edu.cn/f/7670f602d60d48c7b66c/?dl=1) | [validtest](https://cloud.tsinghua.edu.cn/f/0e737b8dcd3a4854bd19/?dl=1)

Sorry but note that I lost the files containing source texts of WMT14, and manage to recover them from the original dataset.  It is unlikely but if you find any problem when using WMT14 data (such as mistakenly paring some sources and targets), please let me know. Thank you very much!

Some Details:
The distilled dataset contains less samples than the original one because some sentences exceed the max length of our AT teacher. To recover the source file, I have to align the source and target texts.  Fortunately, the sample order remains unchanged. I just achieve it by removing some lines in the original dataset.

**Comment by boom-R123** [comment]
Thank you very much! 
Are you using the original dictionaries of WMT14 EN-DE and WMT17 EN-ZH?

**Comment by hzhwcmhf** [comment]
Yes. Here are the dictionaries:  [En-De](https://cloud.tsinghua.edu.cn/f/4653a81dfb5745c4afbd/?dl=1)  [Zh-En](https://cloud.tsinghua.edu.cn/f/70d8e9deea424690a314/?dl=1)

**Comment by boom-R123** [comment]
OK. Thanks again!!
